spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ms-authentication
          uri: lb://ms-authentication
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: ms-authentication
                fallbackUri: forward:/ms-authentication-fallback

        - id: ms-management
          uri: lb://ms-management
          predicates:
            - Path=/courses/**
          filters:
            - CustomGatewayFilter

management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

resilience4j:
  circuitbreaker:
    instances:
      ms-authentication:
        slidingWindowSize: 10                     #unit request
        permittedNumberOfCallsInHalfOpenState: 5  #unit request
        failureRateThreshold: 50                  #percent
        waitDurationInOpenState: 10000            #10 seconds
        registerHealthIndicator: true

server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

